version: '3.9'
services:
  db:
    image: mariadb:10.3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somemariadb 
      MYSQL_DATABASE: mariadb 
      MYSQL_USER: mariadb 
      MYSQL_PASSWORD: mariadb


  phpmyadmin:
    image: phpmyadmin:latest
    links:
      - db
    ports:
      - 8080:80 
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      restart: always
volumes: 
  db_data: {}